project:
  type: website
  output-dir: docs

website:
  title: "thirstforknowledge"
  site-url: https://www.myblogexample.io
  description: "A great sample blog"
  navbar:
    background: dark
    foreground: white
    search: true
    left:
      - text: "Home"
        file: index.qmd
      # - text: "Interview Prep"
      #   file: interview_prep.qmd
      - about.qmd
    # right:
    #   - about.qmd
    #   - icon: github
    #     href: https://github.com/
    #   - icon: twitter
    #     href: https://twitter.com
      # - icon: rss
      #   href: index.xml
format:
  html:
    theme: default
    css: styles.css



